[theme]
primaryColor = "#0D6EFD"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "inter"

[server]
headless = true
runOnSave = true
address = "0.0.0.0"
enableCORS = false
port = 8502
